export const ADD_GRUDGE = 'ADD_GRUDGE';
export const ADD_GRUDGE_SUCCESS = 'ADD_GRUDGE_SUCCESS';
export const TOGGLE_FORGIVENESS = 'TOGGLE_FORGIVENESS';
export const TOGGLE_FORGIVENESS_SUCCESS = 'TOGGLE_FORGIVENESS_SUCCESS';
